# get python on the box
- hosts: all
  remote_user: {{ remote_user }}
  sudo: True
  gather_facts: False
  tasks:
    - raw: python2 --version || pacman -Sy --noconfirm python2

# install basics
- hosts: all
  user: vagrant
  sudo: True
  gather_facts: True
  vars_files:
    - vars/defaults.yml
    - vars/user.yml
  roles:
    - common
    - dotfiles
    - emacs
    - aur
    - x
    - aur
