# put dotfiles into place

- name: make directory
  file: path={{ dotfiles_dest }} state=directory
  sudo_user: "{{ user }}"

- name: clone into place
  action: git repo={{ dotfiles_repo }} dest={{ dotfiles_dest }}
  sudo_user: "{{ user }}"

- name: install command
  pip: name=dotfiles executable=/usr/bin/pip2

- name: connect to repo
  command: ln -sf {{ dotfiles_dest }} /home/{{ user }}/Dotfiles
  sudo_user: "{{ user }}"

- name: sync
  command: dotfiles --sync || dotfiles --sync --force
  sudo_user: "{{ user }}"
