- name: install xorg packages
  pacman: pkg={{ item }} state=installed
  with_items:
    - xorg-xinit
    - xorg-xrdb
    - xorg-xset
    - xorg-xsetroot
    - pkgfile
    - rxvt-unicode
    - dmenu
    - ttf-inconsolata

- name: install conkeror
  command: yaourt -S conkeror-git --noconfirm
