- name: install xorg packages
  pacman: pkg={{ item }} state=installed
  with_items:
    - xorg-xinit
    - xorg-xrdb
    - xorg-xset
    - xorg-xsetroot
    - pkgfile
    - rxvt-unicode
    - dmenu
    - ttf-inconsolata
    - xscreensaver

- name: install conkeror
  command: yaourt -S conkeror-git --noconfirm

- name: install xmonad
  pacman: pkg={{ item }} state=installed
  with_items:
    - xmonad
    - xmonad-contrib
    - xmobar
