- name: install xorg packages
  pacman: pkg={{ item }} state=installed
  with_items:
    - xorg-xinit
    - xorg-xrdb
    - xorg-xset
    - xorg-xsetroot
    - pkgfile
    - rxvt-unicode
    - dmenu
    - ttf-inconsolata
    - xscreensaver
    - chromium

- name: install conkeror
  command: yaourt -S conkeror-git --noconfirm

- name: install dropbox
  command: yaourt -S dropbox dropbox-cli --noconfirm

- name: install dropbox
  command: yaourt -S mu --noconfirm

- name: install xmonad
  pacman: pkg={{ item }} state=installed
  with_items:
    - xmonad
    - xmonad-contrib
    - xmobar

- name: configure emacs gtk
  command: gconftool-2 -t string --set /desktop/gnome/interface/gtk_key_theme Emacs
