- name: install xorg packages
  pacman: pkg={{ item }} state=installed
  with_items:
    - xorg-xinit
    - xorg-xrdb
    - xorg-xset
    - xorg-xsetroot
    - pkgfile
    - rxvt-unicode
    - dmenu
    - ttf-inconsolata
    - xscreensaver
    - chromium
    - chromium-pepper-flash
    - libreoffice
    - maim
    - slop
    - urxvt-perls
    - xsel

- name install yaourt packages
  command: yaourt -S {{ item }} --noconfirm
  with_items:
    - html2text-with-utf8
    - mu
    - libpurple-meanwhile
    - bitlbee-libpurple
    - dropbox
    - dropbox-cli
    - conkeror-git

- name: install xmonad
  pacman: pkg={{ item }} state=installed
  with_items:
    - xmonad
    - xmonad-contrib
    - xmobar

- name: configure emacs gtk
  command: gconftool-2 -t string --set /desktop/gnome/interface/gtk_key_theme Emacs
