- name: add yaourt repo
  lineinfile: dest=/etc/pacman.conf regexp="{{ item | replace('[', '\[') | replace(']', '\]') }}" insertafter=EOF line="{{ item }}"
  with_items:
    - '[archlinuxfr]'
    - 'SigLevel = Never'

- name: add yaourt repo url
  lineinfile: dest=/etc/pacman.conf regexp="repo.archlinux.fr" insertafter=EOF line="Server = http://repo.archlinux.fr/$arch"

- name: install yaourt
  pacman: pkg=yaourt state=installed update_cache=yes
