---
# base setup tasks

- name: update pacman
  pacman: name=pacman state=installed update_cache=yes

- name: init pacman keys
  command: pacman-key --init

- name: update pacman keys
  command: pacman-key --populate archlinux

- name: install basics packages
  pacman: pkg={{ item }} state=installed
  with_items:
    - emacs
    - htop
    - zsh
    - git
    - tmux
    - wget
    - python2-pip
    - xclip
    - hub
    - traceroute
    - sshpass
    - docker

- name: enable docker
  service: name=docker state=started enabled=yes

- name: default pip2
  command: ln -sf /usr/bin/pip2 /usr/local/bin/pip

- name: default python2
  command: ln -sf /usr/bin/python2 /usr/local/bin/python

- name: install basic python pacakges
  pip: name={{ item }} executable=/usr/bin/pip2
  with_items:
    - virtualenvwrapper
    - httpie
    - elpy
    - ipython
    - ansible
    - jedi
    - rope

- include: user.yml
