---
# base setup tasks

- name: update pacman
  pacman: name=pacman state=installed update_cache=yes

- name: Install basics
  pacman: pkg={{ item }} state=installed
  with_items:
    - sudo
    - emacs
    - htop
    - zsh
    - git
    - tmux
    - curl
    - wget
