---
# base setup tasks

- name: update pacman
  pacman: name=pacman state=installed update_cache=yes

- name: update pacman keys
  command: pacman-key --init && pacman-key --populate archlinux

- name: install basics packages
  pacman: pkg={{ item }} state=installed
  with_items:
    - emacs
    - htop
    - zsh
    - git
    - tmux
    - wget
    - python2-pip
    - xclip
    - hub

- name: default pip2
  command: ln -sf /usr/bin/pip2 /usr/local/bin/pip

- name: default python2
  command: ln -sf /usr/bin/python2 /usr/local/bin/python

- name: install basic python pacakges
  pip: name={{ item }} executable=/usr/bin/pip2
  with_items:
    - virtualenvwrapper
    - httpie

- include: user.yml
